before_script:
  - curl -k -L -o selenium.jar http://selenium.googlecode.com/files/selenium-server-standalone-2.33.0.jar
  - java -jar selenium.jar > selenium.out &
  - curl -k -L -o chromedriver.zip http://chromedriver.googlecode.com/files/chromedriver_linux64_26.0.1383.0.zip
  - unzip chromedriver.zip
  - export PATH=$PWD:$PATH
  - sh -e /etc/init.d/xvfb start
  - sleep 10

language: python
python:
  - 2.6
  - 2.7

install: python setup.py install

script: py.test testing/ -m 'not (chrome or opera)'

env:
  - DISPLAY=':99.0'

notifications:
  email:
    - dave.hunt@gmail.com
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
