language: python
python:
  - 2.6
  - 2.7
install:
  - pip install flake8
  - python setup.py install
before_script:
  - flake8 .
  - sh -e /etc/init.d/xvfb start
  - sleep 10
script: py.test testing
env: DISPLAY=':99.0'
