language: python
python:
  - 2.6
  - 2.7
env:
  global:
    - DISPLAY=':99.0'
  matrix:
    - PYTEST=2.4.2
    - PYTEST=2.5.2
    - PYTEST=2.6.4
    - PYTEST=2.7.2
install:
  - pip install flake8
  - pip install -q pytest==$PYTEST
  - pip install -q -e .
before_script:
  - sh -e /etc/init.d/xvfb start
  - flake8 .
script:
  - py.test testing
