language: python
sudo: false
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TOXENV=py26-pytest27
    - TOXENV=py26-pytest28
    - TOXENV=py27-pytest27
    - TOXENV=py27-pytest28
    - TOXENV=py32-pytest27
    - TOXENV=py32-pytest28
    - TOXENV=py33-pytest27
    - TOXENV=py33-pytest28
    - TOXENV=py34-pytest27
    - TOXENV=py34-pytest28
    - TOXENV=pypy-pytest27
    - TOXENV=pypy-pytest28
    - TOXENV=pypy3-pytest27
    - TOXENV=pypy3-pytest28
    - TOXENV=docs
    - TOXENV=flake8
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py32-pytest27
    - env: TOXENV=py32-pytest28
    - env: TOXENV=py33-pytest27
    - env: TOXENV=py33-pytest28
    - env: TOXENV=py34-pytest27
    - env: TOXENV=py34-pytest28
    - env: TOXENV=pypy3-pytest27
    - env: TOXENV=pypy3-pytest28
install:
  - pip install tox
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - tox
