language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
  - nightly
sudo: false
env:
  global:
    - DISPLAY=:99.0
    - PYTEST_ADDOPS="-m 'not (chrome or safari or phantomjs)'"
  matrix:
    - TOXENV=pytest29
    - TOXENV=pytest30
matrix:
  include:
    - python: 2.7
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=flake8
install:
  - pip install tox-travis
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - tox
