language: python
python:
  - 2.6
  - 2.7
install:
  - pip install flake8
  - python setup.py install
before_script:
  - flake8 .
  - curl -k -L -o chromedriver.zip http://chromedriver.googlecode.com/files/chromedriver_linux64_26.0.1383.0.zip
  - unzip chromedriver.zip
  - export PATH=$PWD:$PATH
  - sh -e /etc/init.d/xvfb start
  - sleep 10
script: py.test testing -m 'not (chrome or opera)'
env: DISPLAY=':99.0'
